{% set name = "varname" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/varname-{{ version }}.tar.gz
  sha256: ffb4feadaab35669f43e91d64b8732b2f6514b5b92e659a8c9553a583400c9e1

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - asttokens >=2.0.0,<3.0.0
    - executing >=0.8.3,<0.9.0
    - pure_eval <1.0.0
    - python >=3.6

test:
  imports:
    - varname
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/python-varname
  summary: Dark magics about variable names in python.
  license: MIT
  # Check with upstream for license file
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
